[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6
#decorations = "None"
decorations = "Buttonless"

opacity = 0.2
blur = true

option_as_alt = "Both"

[font]
normal.family = "DaddyTimeMono Nerd Font"
size = 16
#style = "Retina"
#AppleFontSmoothing = "true"

[cursor]
# blinking = "on"
# vi_modde_style = "Beam"
